# Generated by Django 3.1.7 on 2023-01-18 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=200)),
                ('blog_category', models.CharField(max_length=200)),
                ('blog_content', models.CharField(max_length=30000)),
                ('blog_summary', models.CharField(max_length=30000)),
            ],
        ),
    ]
